Welcome to python.  Let's take a quick look at some basic operations

The 'print' function works with strings and string variables as shown below:

In [1]:
print("hello")
string_var = 'world'
print(string_var)
print("hello "+string_var)
print(type(string_var))

hello
world
hello world
<class 'str'>


For loops do the same operation a number of times.  Everything indented is repeated in the loop (this is known as whitespace in python).

In [2]:
x = 1
for i in range(5):
    x += i
    print(i, x)
print(x)

0 1
1 2
2 4
3 7
4 11
11


Python has standard libraries that can be imported and a number of useful functions can then be called.  Numpy.arange produces an array of numbers counting up to the value given in the argument.

In [3]:
!pip install numpy

In [4]:
import numpy as np

In [5]:
x_arr = np.arange(10)

print(x_arr)

[0 1 2 3 4 5 6 7 8 9]


If/else: statements are logical tests that have different outcomes depending on the conditions that are set.

In [6]:
for i in x_arr:
    if i > 3:
        print(i)
    else:
        print(0)

0
0
0
0
4
5
6
7
8
9


Standard array operations are as follows:

In [7]:
x_arr = x_arr + 2
print(x_arr)

x_arr = x_arr * 2
print(x_arr)

[ 2  3  4  5  6  7  8  9 10 11]
[ 4  6  8 10 12 14 16 18 20 22]


Definitions can be set as functions to be called at a later stage to perform tasks without duplicating written code.

In [8]:
def sum_numbers(num1,num2):
    total = num1 + num2
    return total

In [9]:
z = sum_numbers(5,8)
print(z)

13


These can take arguments that are local variables that will not be able to be called outside of that function.

In [10]:
print(num1)

NameError: name 'num1' is not defined

Variables that can be called in and out of functions are called global variables